### ISSUE TITLE
the version of fused_ssim is 0.0.0

### ISSUE THREAD

**Issue by sevennnn07** [rahul-goel/fused-ssim#5]
hello! thanks for your contribution! I got a trouble:
after I run the `pip install git+https://github.com/rahul-goel/fused-ssim/`, the version of it is 0.0.0. I want to know why it happened and how I solve it. thankyou!

**Comment by rahul-goel** [comment]
Hi. I'm not bothering with any Python Packaging yet so the version number doesn't matter. Are you able to run the tests?

**Comment by sevennnn07** [comment]
I input the
`python -c "import torch;from fused_ssim import fused_ssim"`
and i got this
    from fused_ssim_cuda import fusedssim, fusedssim_backward
ModuleNotFoundError: No module named 'fused_ssim_cuda'

**Comment by rahul-goel** [comment]
Does the installation succeed without any error?

Could you also let me know the environment that you're using? To be specific: the pytorch version, nvcc version, g++ version.

**Comment by sevennnn07** [comment]
This is the output of the terminal after installation:
Collecting git+https://github.com/rahul-goel/fused-ssim/
  Cloning https://github.com/rahul-goel/fused-ssim/ to /tmp/pip-req-build-cs1tw147
  Running command git clone --filter=blob:none --quiet https://github.com/rahul-goel/fused-ssim/ /tmp/pip-req-build-cs1tw147
  Resolved https://github.com/rahul-goel/fused-ssim/ to commit d99e3d27513fa3563d98f74fcd40fd429e9e9b0e
  Preparing metadata (setup.py) ... done

And my environment is:
python version: 3.9.20
nvcc version:  12.1
g++ version: 11.4

**Comment by rahul-goel** [comment]
Hi. I won't be able to resolve this issue and help you with it for 2 weeks since I'm away. Here are probably some things you can try meanwhile:
- Clone the repository and then attempt pip install instead of installing from git directly.
- Ensure that the PyTorch version with CUDA matches the major version 12.
- Ensure that the g++ compiler is supported by CUDA 12. And that it is the compiler used by NVCC has the host compiler.

In the README, there are environments mentioned for which I've tested it (tested on linux). Perhaps, you can switch to it if possible. Hope this helps for now.

**Comment by sevennnn07** [comment]
Thank you very much!!!! 
I successfully resolved the error by using the first method
